version: '3.8'

services:
  # Laravel Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-todo-api
    restart: always
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000"
    networks:
      - app-network

  # PHPMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8080:80"
    restart: always
    depends_on:
      - mysql
    networks:
      - app-network

  # MySQL
  mysql:
    image: mysql:8.0
    container_name: laravel_todo_db
    restart: always
    environment:
      MYSQL_DATABASE: laravel_todo
      MYSQL_USER: laravelUser
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root_secret
    ports:
      - "3306:3306"
    networks:
      - app-network

  # MailHog
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    restart: always
    ports:
      - "8025:8025"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
